### ISSUE TITLE
where is the kern and ndlutil package?

### ISSUE THREAD

**Issue by DragonCircle** [lawrennd/gplvm#1]
in this python file 
[https://github.com/lawrennd/gplvm/blob/master/python/gplvm_simple.py](url)
`sys.path.append('/home/james/mlprojects/kern/python')
sys.path.append('/home/james/mlprojects/ndlutil/python')
import kern
import ndlutil`
you import two package,
where can I find those packages?
thank you very much!

**Comment by lawrennd** [comment]
I think you've stumbled across some old legacy code!

It's dim in my memory, but I think you're looking for this: https://github.com/lawrennd/kern/tree/master/python

and this:

https://github.com/lawrennd/ndlutil/tree/master/python

But this work transformed into GPy, which is here: https://github.com/SheffieldML/GPy

**Comment by DragonCircle** [comment]
Thank you! 
I know GPy, a great GP python package!
However, I just want some clean python code that implement GPR and GP-LVM, ,without much abstraction, so that I can figure out how the model learns from the data, how the marginal likelihood is calculated ,and how the gradients derived.
And I found this old code very helpful!
Thank you!

**Comment by DragonCircle** [comment]
Actually I'm trying to implement Warped GP in this paper[http://www.gatsby.ucl.ac.uk/~snelson/gpwarp.pdf](url).
Just some small modification based on the original GPR,
Do you have any advice, Prof. Lawrence?

**Comment by lawrennd** [comment]
No particular advice on warped GPs beyond what’s in the paper, but if
you’re interested in the regular GP and how it comes together, second part
of this notebook:

https://github.com/lawrennd/mlai2015/blob/master/week12.ipynb


Is targeted at that.

Neil

**Comment by DragonCircle** [comment]
Another GP question, last one! 
I'm trying to compare Variational AutoEncoder(VAE) and GP-LVM in some cases.
Can I say that the fundamentally difference between them, is the mapping function **f** from latent space **X** to observation space **Y**?
In GP-LVM **f**~_GP_ , and in VAE **f** is a MLP?
Is that claim right?
I found GP based model much more stable than NN based models, because we don't need to tune many hyperparameters, but why people focus on VAE and GAN recently rather than GPLVM or DeepGPs?
I know I am being a free rider, but you are an GP expert! I will do my research by myself anyway, but it's great to hear your thought!

**Comment by lawrennd** [comment]
Yes, that’s broadly true. Although variational auto-encoders do latent space with an encoder, but GP-LVM can also do that (that’s called variational autoencoder). We’ve also done that for Deep GPs (ICLR paper from 2016).

The NN models are easier to scale to large data from a learning algorithm perspective. But for low data I think the GP-based models are still state of the art. 

GANs actually optimize a different objective function than the NN models. For that reason (for example) it is perfectly conceivable to envisage a GP-GAN which could optimize that objective. The GAN objectives have a characteristic which, different from maximum likelihood, they don’t cover the whole distribution of the data, but tend to focus on particular modes of data.

**Comment by DragonCircle** [comment]
Thank you, Prof. Lawrence! Hearing your thought is better than weeks of research!
Looking forward to that GP-GAN paper!(Can I ask who is working on this idea now?)
Speaking of the scalability of GP models, I read some papers about Sparse Gaussian Processes recently, It seems to me that the complexity of O(NM^2) is good enough(better than SVM's O(N^2) if M<sqrt(N) I think?) for practical application. But I haven't seen a comparison between SGP based models and NN based models(where SGP models only output mean prediction). Can I ask what is the fundamental reason (you think) that hinders GP from practical application like DNNs?
I may have been annoying, but I'm really curious about GPs case the uncertainty it represent is so attractive, and also makes the GP model extensible on practical use(anomaly detection, decision making, etc.), I don't have any expert to ask but you!

**Comment by lawrennd** [comment]
Well, actually there are proofs that M needs to be O(\sqrt{N}) so things in
worst case come back to O(N^2)!

I agree about the attractiveness of GPs as representing uncertainty, it's
quite hard to retrofit elegantly to a model, so it seems worth perservering
making them practical.

I don't know of anyone working on GP-GANs at the moment, but I wouldn't be
surprised if someone did, maybe you should try it!

**Comment by DragonCircle** [comment]
Well, it seems like that the O(N^2) computation complexity is inevitable, maybe only quantum computer can save us, haha~, case there is a promising quantum Bayesianism theory(I'm a layman, just heard about it).

**Comment by DragonCircle** [comment]
It seems like that the O(N^2) computation complexity is inevitable, maybe only quantum computer can save us, haha~, case there is a promising quantum Bayesianism theory(I'm a layman, just heard about it), maybe we don't have to worry about the intractable denominator anymore in the future!
I'm focusing on GP methods for data mining, and one of my friend(under the same tutor)'s work is based on your student's GP for Differential Privacy Regression work! Because we found that the GP-DP work is complete in theory, and we are trying to extend it to other data! We are just starting up, and we are very thankful for your encouragement!
